#pragma once

#include "app_types.h"

typedef enum {
    LOC_STATUS_IDLE,
    LOC_STATUS_ERROR,
    LOC_STATUS_PLAYING,
    LOC_STATUS_BUFFERING,
    LOC_STATUS_STOPPED,
    LOC_STATE,
    LOC_LISTENING_ON,
    LOC_SOURCE,
    LOC_NOT_CONNECTED,
    LOC_BUFFER_FORMAT,
    LOC_RECEIVED_FORMAT,
    LOC_DROPPED_FORMAT,
    LOC_UNDERRUNS_FORMAT,
    LOC_ERROR_TITLE,
    LOC_ERROR_ACTIONS,
    LOC_SETTINGS_TITLE,
    LOC_UDP_PORT,
    LOC_BUFFER,
    LOC_VOLUME,
    LOC_LANGUAGE,
    LOC_UNSAVED_CHANGES,
    LOC_SETTINGS_APPLIED,
    LOC_LOG_ON,
    LOC_LOG_OFF,
    LOC_CONTROLS_SELECT_CHANGE,
    LOC_CONTROLS_ACTIONS,
    LOC_CONTROLS_SYSTEM,
    LOC_NOTICE_LOG_DISABLED,
    LOC_NOTICE_LOG_ENABLED,
    LOC_NOTICE_LOG_NO_MEMORY,
    LOC_NOTICE_SETTINGS_SAVED,
    LOC_NOTICE_SOURCE_DISCONNECTED,
    LOC_NOTICE_LANGUAGE_JAPANESE,
    LOC_NOTICE_LANGUAGE_ENGLISH,
    LOC_ERROR_RING_MEMORY,
    LOC_COUNT
} LocKey;

const char *loc_get(AppLanguage language, LocKey key);
