#include "localization.h"

static const char *const JAPANESE[LOC_COUNT] = {
    [LOC_STATUS_IDLE] = "待機中",
    [LOC_STATUS_ERROR] = "エラー",
    [LOC_STATUS_PLAYING] = "再生中",
    [LOC_STATUS_BUFFERING] = "バッファリング",
    [LOC_STATUS_STOPPED] = "停止中",
    [LOC_STATE] = "状態",
    [LOC_LISTENING_ON] = "受信先",
    [LOC_SOURCE] = "送信元",
    [LOC_NOT_CONNECTED] = "未接続",
    [LOC_BUFFER_FORMAT] = "バッファ %.1f / %u ms",
    [LOC_RECEIVED_FORMAT] = "受信 %llu packets / %llu KiB",
    [LOC_DROPPED_FORMAT] = "破棄 %llu KiB  不正 %llu  他送信元 %llu",
    [LOC_UNDERRUNS_FORMAT] = "アンダーラン %lu",
    [LOC_ERROR_TITLE] = "初期化・設定エラー",
    [LOC_ERROR_ACTIONS] = "A: 再試行   START: 終了",
    [LOC_SETTINGS_TITLE] = "受信設定",
    [LOC_UDP_PORT] = "UDPポート",
    [LOC_BUFFER] = "バッファ",
    [LOC_VOLUME] = "音量",
    [LOC_LANGUAGE] = "言語 / Language",
    [LOC_UNSAVED_CHANGES] = "未適用の変更があります",
    [LOC_SETTINGS_APPLIED] = "設定は適用済みです",
    [LOC_LOG_ON] = "診断ログ: 有効（終了時に保存）",
    [LOC_LOG_OFF] = "診断ログ: 無効（Yで有効化）",
    [LOC_CONTROLS_SELECT_CHANGE] = "↑↓ 選択  ←→ 変更  L/R ポート±100",
    [LOC_CONTROLS_ACTIONS] = "A 保存  X 切断  Y 診断ログ",
    [LOC_CONTROLS_SYSTEM] = "SELECT 言語切替  START 終了",
    [LOC_NOTICE_LOG_DISABLED] = "診断ログを無効化しました",
    [LOC_NOTICE_LOG_ENABLED] = "診断ログを有効化しました",
    [LOC_NOTICE_LOG_NO_MEMORY] = "診断ログ用メモリを確保できません",
    [LOC_NOTICE_SETTINGS_SAVED] = "設定を保存・適用しました",
    [LOC_NOTICE_SOURCE_DISCONNECTED] = "送信元を切断しました",
    [LOC_NOTICE_LANGUAGE_JAPANESE] = "表示言語: 日本語（Aで保存）",
    [LOC_NOTICE_LANGUAGE_ENGLISH] = "Display language: English (A to save)",
    [LOC_ERROR_RING_MEMORY] = "リングバッファのメモリ確保に失敗しました",
};

static const char *const ENGLISH[LOC_COUNT] = {
    [LOC_STATUS_IDLE] = "Idle",
    [LOC_STATUS_ERROR] = "Error",
    [LOC_STATUS_PLAYING] = "Playing",
    [LOC_STATUS_BUFFERING] = "Buffering",
    [LOC_STATUS_STOPPED] = "Stopped",
    [LOC_STATE] = "Status",
    [LOC_LISTENING_ON] = "Listening on",
    [LOC_SOURCE] = "Source",
    [LOC_NOT_CONNECTED] = "Not connected",
    [LOC_BUFFER_FORMAT] = "Buffer %.1f / %u ms",
    [LOC_RECEIVED_FORMAT] = "Received %llu packets / %llu KiB",
    [LOC_DROPPED_FORMAT] = "Dropped %llu KiB  Invalid %llu  Foreign %llu",
    [LOC_UNDERRUNS_FORMAT] = "Underruns %lu",
    [LOC_ERROR_TITLE] = "Initialization / settings error",
    [LOC_ERROR_ACTIONS] = "A: Retry   START: Exit",
    [LOC_SETTINGS_TITLE] = "Receiver settings",
    [LOC_UDP_PORT] = "UDP port",
    [LOC_BUFFER] = "Buffer",
    [LOC_VOLUME] = "Volume",
    [LOC_LANGUAGE] = "Language / 言語",
    [LOC_UNSAVED_CHANGES] = "Changes have not been applied",
    [LOC_SETTINGS_APPLIED] = "Settings are applied",
    [LOC_LOG_ON] = "Diagnostic log: On (saved on exit)",
    [LOC_LOG_OFF] = "Diagnostic log: Off (Y to enable)",
    [LOC_CONTROLS_SELECT_CHANGE] = "↑↓ Select  ←→ Change  L/R Port ±100",
    [LOC_CONTROLS_ACTIONS] = "A Save  X Disconnect  Y Diagnostic log",
    [LOC_CONTROLS_SYSTEM] = "SELECT Language  START Exit",
    [LOC_NOTICE_LOG_DISABLED] = "Diagnostic logging disabled",
    [LOC_NOTICE_LOG_ENABLED] = "Diagnostic logging enabled",
    [LOC_NOTICE_LOG_NO_MEMORY] = "Not enough memory for diagnostic log",
    [LOC_NOTICE_SETTINGS_SAVED] = "Settings saved and applied",
    [LOC_NOTICE_SOURCE_DISCONNECTED] = "Audio source disconnected",
    [LOC_NOTICE_LANGUAGE_JAPANESE] = "表示言語: 日本語（Aで保存）",
    [LOC_NOTICE_LANGUAGE_ENGLISH] = "Display language: English (A to save)",
    [LOC_ERROR_RING_MEMORY] = "Could not allocate ring buffer memory",
};

const char *loc_get(AppLanguage language, LocKey key) {
    if (key >= LOC_COUNT) return "";
    return language == APP_LANGUAGE_ENGLISH ? ENGLISH[key] : JAPANESE[key];
}
